# fly.toml app configuration file generated for port-proud-bush-2749 on 2025-06-07T23:23:37-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'port-proud-bush-2749'
primary_region = 'lax'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
